//@version=4
//Basic Hull Ma Pack tinkered by InSilico 
//Converted to Strategy by DashTrader
strategy("Hull Suite Strategy", overlay=true, pyramiding=1, default_qty_type = strategy.cash, default_qty_value = 500, calc_on_order_fills=false, slippage=0,commission_type=strategy.commission.percent,commission_value=0.04)

strat_dir_input = input(title="Strategy Direction", defval="all", options=["long", "short", "all"], group="Main Settings")
strat_dir_value = strat_dir_input == "long" ? strategy.direction.long : strat_dir_input == "short" ? strategy.direction.short : strategy.direction.all
strategy.risk.allow_entry_in(strat_dir_value)
//////////////////////////////////////////////////////////////////////
// Testing Start dates
testStartYear = input(2016, "Backtest Start Year", group="Main Settings")
testStartMonth = input(1, "Backtest Start Month", group="Main Settings")
testStartDay = input(1, "Backtest Start Day", group="Main Settings")
testStartHour = input(0, "Backtest Start Hour", group="Main Settings")
testStartMinute = input(0, "Backtest Start Minute", group="Main Settings")
testPeriodStart = timestamp(testStartYear,testStartMonth,testStartDay,testStartHour,testStartMinute)
//Stop date if you want to use a specific range of dates
testStopYear = input(2030, "Backtest Stop Year", group="Main Settings")
testStopMonth = input(12, "Backtest Stop Month", group="Main Settings")
testStopDay = input(30, "Backtest Stop Day", group="Main Settings")
testPeriodStop = timestamp(testStopYear,testStopMonth,testStopDay,0,0)


testPeriod() =>
    time >= testPeriodStart and time <= testPeriodStop ? true : false
// Component Code Stop
//////////////////////////////////////////////////////////////////////
//INPUT
src = input(close, title="Source")
modeSwitch = input("Hma", title="Hull Variation", options=["Hma", "Thma", "Ehma"])
length = input(55, title="Length(180-200 for floating S/R , 55 for swing entry)")
switchColor = input(true, "Color Hull according to trend?")
candleCol = input(false,title="Color candles based on Hull's Trend?")
visualSwitch  = input(true, title="Show as a Band?")
thicknesSwitch = input(1, title="Line Thickness")
transpSwitch = input(40, title="Band Transparency",step=5)

//FUNCTIONS
//HMA
HMA(_src, _length) =>  wma(2 * wma(_src, _length / 2) - wma(_src, _length), round(sqrt(_length)))
//EHMA    
EHMA(_src, _length) =>  ema(2 * ema(_src, _length / 2) - ema(_src, _length), round(sqrt(_length)))
//THMA    
THMA(_src, _length) =>  wma(wma(_src,_length / 3) * 3 - wma(_src, _length / 2) - wma(_src, _length), _length)
    
//SWITCH
Mode(modeSwitch, src, len) =>
      modeSwitch == "Hma"  ? HMA(src, len) :
      modeSwitch == "Ehma" ? EHMA(src, len) : 
      modeSwitch == "Thma" ? THMA(src, len/2) : na
      
//OUT
HULL = Mode(modeSwitch, src, length)
MHULL = HULL[0]
SHULL = HULL[2]

//COLOR
hullColor = switchColor ? (HULL > HULL[2] ? #00ff00 : #ff0000) : #ff9800

//PLOT
///< Frame
Fi1 = plot(MHULL, title="MHULL", color=hullColor, linewidth=thicknesSwitch, transp=50)
Fi2 = plot(visualSwitch ? SHULL : na, title="SHULL", color=hullColor, linewidth=thicknesSwitch, transp=50)
///< Ending Filler
fill(Fi1, Fi2, title="Band Filler", color=hullColor, transp=transpSwitch)
///BARCOLOR
barcolor(color = candleCol ? (switchColor ? hullColor : na) : na)

// new codes ======================================================================================

// adx ================================================================================================

adxlen = input(14, title="ADX Smoothing", group="ADX Settings")
dilen = input(14, title="DI Length", group="ADX Settings")
adxlevel = input(23, title="Starting ADX", group="ADX Settings")

[diplus, diminus, adx] = dmi(dilen, adxlen)

activation = input(1.0, title="Activation (%)", group="Trailing Stop", step=0.1)
callback = input(1.0, title="Callback (%)", group="Trailing Stop", step=0.1)
loss = input(1.0, title="Stop (%)", group="Trailing Stop", step=0.1)

trailActivation = close * (activation * 0.01) / syminfo.mintick
trailOffset = close * (callback * 0.01) / syminfo.mintick
stop = close * (loss * 0.01) / syminfo.mintick

alert_message = ""


if HULL[0] > HULL[2] and testPeriod() and adx > adxlevel

    if strategy.position_size < 0
        // close short bot and open long bot
        alert_message := "[{\"action\":\"close_at_market_price\",\"message_type\":\"bot\",\"bot_id\":7284327,\"email_token\":\"331c8ed8-a6bf-4730-bbad-f4f579c0c06d\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"},{\"message_type\":\"bot\",\"bot_id\":7279290,\"email_token\":\"306730f0-57f3-4f17-b1ee-2ec10c6ed852\",\"delay_seconds\":3,\"pair\":\"USDT_GALAUSDT\"}]"                        
    else
        // open long bot
        alert_message := "{\"message_type\":\"bot\",\"bot_id\":7279290,\"email_token\":\"306730f0-57f3-4f17-b1ee-2ec10c6ed852\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"}"

    strategy.entry("buy", strategy.long, comment=alert_message)
    
    // close long bot
    alert_message := "{\"action\":\"close_at_market_price\",\"message_type\":\"bot\",\"bot_id\":7279290,\"email_token\":\"306730f0-57f3-4f17-b1ee-2ec10c6ed852\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"}"
    strategy.exit("exit-long", "buy", trail_offset=trailOffset, trail_points=trailActivation, loss=stop, comment=alert_message)
    
        
if HULL[0] < HULL[2] and testPeriod() and adx > adxlevel

    if strategy.position_size > 0
        // close long bot and open short bot
        alert_message := "[{\"action\":\"close_at_market_price\",\"message_type\":\"bot\",\"bot_id\":7279290,\"email_token\":\"306730f0-57f3-4f17-b1ee-2ec10c6ed852\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"},{\"message_type\":\"bot\",\"bot_id\":7284327,\"email_token\":\"331c8ed8-a6bf-4730-bbad-f4f579c0c06d\",\"delay_seconds\":3,\"pair\":\"USDT_GALAUSDT\"}]"
    else 
        // open short bot
        alert_message := "{\"message_type\":\"bot\",\"bot_id\":7284327,\"email_token\":\"331c8ed8-a6bf-4730-bbad-f4f579c0c06d\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"}"


    strategy.entry("sell", strategy.short, comment=alert_message)
    
    
    //close short bot
    alert_message := "{\"action\":\"close_at_market_price\",\"message_type\":\"bot\",\"bot_id\":7284327,\"email_token\":\"331c8ed8-a6bf-4730-bbad-f4f579c0c06d\",\"delay_seconds\":0,\"pair\":\"USDT_GALAUSDT\"}"
    strategy.exit("exit-short", "sell", trail_offset=trailOffset, trail_points=trailActivation, loss=stop, comment=alert_message)    
